// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtamsuX-NQhxSTvjWeoI7W3hrc4m7ik10',
    appId: '1:186175118900:web:7de1ec1beaffa58a20b461',
    messagingSenderId: '186175118900',
    projectId: 'cliffstudy-c3b06',
    authDomain: 'cliffstudy-c3b06.firebaseapp.com',
    storageBucket: 'cliffstudy-c3b06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJckmrkhQ70PiYMzKiU_hNOHDH2N52yHI',
    appId: '1:186175118900:android:e4c57e870966b59420b461',
    messagingSenderId: '186175118900',
    projectId: 'cliffstudy-c3b06',
    storageBucket: 'cliffstudy-c3b06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQkyCt2xXGJUfjcKP0QuZl7A5b2HnAOtE',
    appId: '1:186175118900:ios:a565f0b01951460d20b461',
    messagingSenderId: '186175118900',
    projectId: 'cliffstudy-c3b06',
    storageBucket: 'cliffstudy-c3b06.appspot.com',
    iosClientId: '186175118900-q271irarfis5k5od7m68do8ra55q7jsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzPlayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQkyCt2xXGJUfjcKP0QuZl7A5b2HnAOtE',
    appId: '1:186175118900:ios:a565f0b01951460d20b461',
    messagingSenderId: '186175118900',
    projectId: 'cliffstudy-c3b06',
    storageBucket: 'cliffstudy-c3b06.appspot.com',
    iosClientId: '186175118900-q271irarfis5k5od7m68do8ra55q7jsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzPlayApp',
  );
}
